### ISSUE TITLE
CognitoUserPool and API gateway

### ISSUE THREAD

**Issue by JustonJ99** [xfsnow/android#1]
Hi, may I know is it possible to integrated CognitoUserPool and API gateway? Which is after cognito user signed in, user will access to API gateway then get EC2 service. Currently I already successfully allow cognito user and facebook user integrated in identity pool but I have no idea how to allow user access API gateway after signed in. Any suggestion for me? Thank you.

**Comment by JustonJ99** [comment]
Thank you for the reply. Now I would like to integrate your Petstore demo with my user pool. However, when I run the Petstore, the error is 

09-11 18:43:42.403 1165-1282/com.example.petstore E/AndroidRuntime: FATAL EXCEPTION: Thread-68829
    Process: com.example.petstore, PID: 1165

I used debug to run demo instead of the emulator.

**Comment by JustonJ99** [comment]
Thank you for the suggestion, I will try it.
another issue is when I follow your Petstore tutorial [](https://aws.amazon.com/cn/blogs/china/api-gateway-android-sdk/). At the end the error show this

Logcat:
09-12 00:38:15.923 12057-12075/com.example.petstore E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: com.example.petstore, PID: 12057
    com.amazonaws.mobileconnectors.apigateway.ApiClientException: Unable to execute HTTP request: Connection refused (Service: null; Status Code: 0; Error Code: null; Request ID: null)
        at com.amazonaws.mobileconnectors.apigateway.ApiClientHandler.invoke(ApiClientHandler.java:118)
        at java.lang.reflect.Proxy.invoke(Proxy.java:813)
        at $Proxy1.petsGet(Unknown Source)
        at com.example.petstore.MainActivity.testPet(MainActivity.java:36)
        at com.example.petstore.MainActivity.access$000(MainActivity.java:17)
        at com.example.petstore.MainActivity$2.run(MainActivity.java:70)
     Caused by: com.amazonaws.AmazonClientException: Unable to execute HTTP request: Connection refused
